package com.xcu.mapper;

import com.xcu.entity.TbChatRecord;
import com.xcu.entity.TbChatRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbChatRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int countByExample(TbChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int deleteByExample(TbChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int insert(TbChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int insertSelective(TbChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    List<TbChatRecord> selectByExample(TbChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    TbChatRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbChatRecord record, @Param("example") TbChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int updateByExample(@Param("record") TbChatRecord record, @Param("example") TbChatRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int updateByPrimaryKeySelective(TbChatRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chat_record
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int updateByPrimaryKey(TbChatRecord record);
}