package com.xcu.mapper;

import com.xcu.entity.TbFriend;
import com.xcu.entity.TbFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int countByExample(TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int deleteByExample(TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int insert(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int insertSelective(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    List<TbFriend> selectByExample(TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    TbFriend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbFriend record, @Param("example") TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int updateByExample(@Param("record") TbFriend record, @Param("example") TbFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int updateByPrimaryKeySelective(TbFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friend
     *
     * @mbggenerated Sat Aug 15 16:44:00 CST 2020
     */
    int updateByPrimaryKey(TbFriend record);
}